### PR TITLE
 Only scanning directories declared in composer, ignoring vendor and fixtures dirs

### LINKED ISSUE #16: Fixtures folder should be ignored
Folders named ``fixtures`` generally contain test fixtures, which may even be invalid PHP files (to test what happens with files containing a syntax error for instance, or files using a PHP 7 syntax). Analysing them is not needed IMO.

### PR DESCRIPTION
**Pull request by moufmouf**
Closes #16 and #15

### CODE REVIEW

**Comment by stof** [comment]
the diff of the PR looks really weird

**Comment by stof** [comment]
yeah, you duplicated all the recent history of the repo. Looks like you rebased master on top of your changes rather than the opposite

**Comment by stof** [comment]
@moufmouf I suggest you to use feature branches in your fork, creating them from the upstream master branch all the time, instead of using the same branch for all PRs, which causes issues when it diverges

**Comment by moufmouf** [comment]
@stof Yeah, that diff looks real weird... Thanks for the tip about feature branches!

**Comment by stof** [comment]
@moufmouf the diff is because of duplicated commits in the history. and this is why I also always review the diff and the commit list of a PR before merging it

**Comment by marcteyssier** [comment]
Hello! 

I've decided to spend a couple of days in camping, just take a look at that place <http://star.yogalite.net/e4qaiaw>

Thanks for your consideration, m.teyssier

**Pull request merged**
